MYSQL_DB_NAME: my_database
MYSQL_DB_IDENTIFIER: database-1
MYSQL_DB_USERNAME: admin
MYSQL_DB_PASSWORD: '123ali123'
MYSQL_DB_HOST: database-1.cf3vs1vxuiii.us-east-1.rds.amazonaws.com
MYSQL_DB_PORT: 3306
NODE_ENV: dev
REGION: us-east-1